# Generated by Django 3.1 on 2020-11-30 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_company_name', models.CharField(max_length=200)),
                ('train_company_address_province', models.CharField(max_length=80)),
                ('train_company_address_city', models.CharField(max_length=80)),
                ('train_company_address_area', models.CharField(max_length=80)),
                ('train_company_address_info', models.CharField(max_length=500)),
                ('train_company_signcode', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='WorkPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_position_name', models.CharField(max_length=200)),
                ('work_position_type', models.CharField(max_length=80)),
                ('work_position_salary', models.IntegerField(default=0)),
                ('train_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='train_query.traincompany')),
            ],
        ),
    ]
