# Generated by Django 3.1 on 2020-11-30 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train_query', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='traincompany',
            name='is_effective',
            field=models.BooleanField(default=True),
        ),
    ]
